# Generated by Django 5.2.4 on 2025-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_comment_text_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], max_length=10),
        ),
    ]
